openapi: 3.0.0
info:
  description: |
    Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions.
  title: Web of Science Lookup API
  version: 0.1.9
servers:
- description: Not the final URL - TBD
  url: http://api.clarivate.com/woslookup/v1
paths:
  /subscriptions:
    get:
      description: TBD
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscriptions'
          description: Subscription List
      summary: returns application and subscription info for those apps not older
        than 90 days that have not been approved
      x-accepts: application/json
  /SFDCOpportunities:
    get:
      description: TBD
      parameters:
      - description: Filter by SFDC account name or enterprise id
        examples:
          enterpriseId:
            value: ACT-00000000
          accountName:
            value: Harvard University
        explode: true
        in: query
        name: sfdcAccount
        required: false
        schema:
          type: string
        style: form
      - description: Filter by SFDC API Product Code or Name
        examples:
          productCode:
            value: "45021425"
          product:
            value: Journals API - Data Integration
        explode: true
        in: query
        name: sfdcApiProduct
        required: false
        schema:
          type: string
        style: form
      - description: Filter by SFDC Account domain(s)
        explode: true
        in: query
        name: sfdcAccountDomain
        required: false
        schema:
          example: kit.edu
          type: string
        style: form
      - description: Filter by name or email address of internal Clarivate account
        explode: true
        in: query
        name: internalUser
        required: false
        schema:
          type: string
        style: form
      - description: "null"
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      - description: "null"
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SFDCOpportunityList'
          description: Opportunity list
      summary: Returns the list of opportunities
      x-accepts: application/json
    post:
      description: TBD
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              type: object
      responses:
        "201":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: OK
      summary: Update the OPP data by providing an excel file
      x-contentType: multipart/form-data
      x-accepts: application/json
  /SFDCOpportunities/{opportunityID}:
    get:
      description: TBD
      parameters:
      - explode: false
        in: path
        name: opportunityID
        required: true
        schema:
          example: OPP-00000000
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SFDCOpportunity'
          description: Opportunity
      summary: Returns an opportunity by ID
      x-accepts: application/json
  /SFDCAccounts:
    get:
      description: TBD
      parameters:
      - description: Filter by SFDC API Product Code or Name
        explode: true
        in: query
        name: sfdcApiProduct
        required: false
        schema:
          type: string
        style: form
      - description: Filter by SFDC Account Name
        explode: true
        in: query
        name: sfdcAccountName
        required: false
        schema:
          type: string
        style: form
      - description: Filter by SFDC Account domain(s)
        explode: true
        in: query
        name: sfdcAccountDomain
        required: false
        schema:
          example: kit.edu
          type: string
        style: form
      - description: Filter by name or email address of internal Clarivate account
        explode: true
        in: query
        name: internalUser
        required: false
        schema:
          type: string
        style: form
      - description: "null"
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      - description: "null"
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SFDCAccountList'
          description: Accounts list
      summary: Returns the list of SFDC accounts
      x-accepts: application/json
    post:
      description: TBD
      requestBody:
        $ref: '#/components/requestBodies/inline_object_1'
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              type: object
      responses:
        "201":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: OK
      summary: Update the Account data by providing an excel file
      x-contentType: multipart/form-data
      x-accepts: application/json
  /SFDCAccounts/{enterpriseID}:
    get:
      description: TBD
      parameters:
      - explode: false
        in: path
        name: enterpriseID
        required: true
        schema:
          example: ACT-00000000
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SFDCAccount'
          description: Account
      summary: Returns an opportunity by ID
      x-accepts: application/json
  /SFDCInternalUsers:
    get:
      description: TBD
      parameters:
      - description: Filter by name or email address of internal Clarivate account
        explode: true
        in: query
        name: internalUser
        required: false
        schema:
          type: string
        style: form
      - description: "null"
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      - description: "null"
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalUserList'
          description: Accounts list
      summary: Returns the list of SFDC users
      x-accepts: application/json
    post:
      description: TBD
      requestBody:
        $ref: '#/components/requestBodies/inline_object_2'
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              type: object
      responses:
        "201":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: OK
      summary: Update the Internal users data by providing an excel file
      x-contentType: multipart/form-data
      x-accepts: application/json
  /tasks/{id}:
    get:
      description: TBD
      parameters:
      - description: Task id
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                Done:
                  value:
                    id: 54
                    state: DONE
                    startDt: 2021-10-05T00:58:28.516
                    endDt: 2021-10-05T02:59:50.708
                New:
                  value:
                    id: 54
                    state: NEW
                    startDt: 2021-10-05T00:58:28.516
                FailedByTimeout:
                  value:
                    id: 47
                    state: FAILED
                    startDt: 2021-10-05T00:58:28.516
                    endDt: 2021-10-05T02:59:50.708
                    message: Initialization timeout 60 seconds is reached
              schema:
                $ref: '#/components/schemas/Task'
          description: Task
      summary: Returns the task
      x-accepts: application/json
components:
  requestBodies:
    inline_object_1:
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/inline_object_1'
    inline_object:
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/inline_object'
    inline_object_2:
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/inline_object_2'
  schemas:
    SFDCOpportunityList:
      example:
        hits:
        - opportunityRef:
            opportunityIDNumber: OPP-00000000
            ref: /SFDCOpportunities/OPP-00000000
            opportunityName: UNIVERSITE DE POITIERS - Web of Science - 2022
            stage: stage
            type: type
            contractExpireDate: contractExpireDate
          matches:
          - field: field
            value:
            - value
            - value
          - field: field
            value:
            - value
            - value
        - opportunityRef:
            opportunityIDNumber: OPP-00000000
            ref: /SFDCOpportunities/OPP-00000000
            opportunityName: UNIVERSITE DE POITIERS - Web of Science - 2022
            stage: stage
            type: type
            contractExpireDate: contractExpireDate
          matches:
          - field: field
            value:
            - value
            - value
          - field: field
            value:
            - value
            - value
        metadata:
          total: 0
          limit: 1
          page: 6
      properties:
        metadata:
          $ref: '#/components/schemas/Metadata'
        hits:
          items:
            $ref: '#/components/schemas/SFDCOpportunityListRecord'
          type: array
      type: object
    SFDCOpportunityListRecord:
      example:
        opportunityRef:
          opportunityIDNumber: OPP-00000000
          ref: /SFDCOpportunities/OPP-00000000
          opportunityName: UNIVERSITE DE POITIERS - Web of Science - 2022
          stage: stage
          type: type
          contractExpireDate: contractExpireDate
        matches:
        - field: field
          value:
          - value
          - value
        - field: field
          value:
          - value
          - value
      properties:
        opportunityRef:
          $ref: '#/components/schemas/SFDCOpportunityReference'
        matches:
          items:
            $ref: '#/components/schemas/SearchMatch'
          type: array
      type: object
    SFDCAccountListRecord:
      example:
        accountRef:
          ref: /SFDCAccounts/ACT-0000000
          accountName: Clarivate
          enterpriseId: ACT-0000000
        matches:
        - field: field
          value:
          - value
          - value
        - field: field
          value:
          - value
          - value
      properties:
        accountRef:
          $ref: '#/components/schemas/SFDCAccountReference'
        matches:
          items:
            $ref: '#/components/schemas/SearchMatch'
          type: array
      type: object
    SFDCOpportunityReference:
      example:
        opportunityIDNumber: OPP-00000000
        ref: /SFDCOpportunities/OPP-00000000
        opportunityName: UNIVERSITE DE POITIERS - Web of Science - 2022
        stage: stage
        type: type
        contractExpireDate: contractExpireDate
      properties:
        opportunityIDNumber:
          description: Opportunity ID Number that is can be used in emails
          example: OPP-00000000
          type: string
        opportunityName:
          description: Opportunity name
          example: UNIVERSITE DE POITIERS - Web of Science - 2022
          type: string
        ref:
          description: Link to the full SFDC opportunity data
          example: /SFDCOpportunities/OPP-00000000
          type: string
        type:
          description: Type of opportunity, New, Renewal, Amendment, etc.
          type: string
        contractExpireDate:
          type: string
        stage:
          type: string
      type: object
    SFDCInternal:
      properties:
        name:
          type: String
      type: object
    SFDCAccount:
      example:
        emailDomain: slv.vic.gov.au
        caesarReference:
          trialEnd: trialEnd
          soldTo: soldTo
          accountName: accountName
          trialStart: trialStart
          customerId: customerId
          identifierSet:
          - soldTo: soldTo
            identifierList:
            - kind: kind
              value: value
            - kind: kind
              value: value
            customApps:
            - customApps
            - customApps
            name: name
            id: id
            entitlementSet:
            - entitlementSet
            - entitlementSet
            shipTo: shipTo
          - soldTo: soldTo
            identifierList:
            - kind: kind
              value: value
            - kind: kind
              value: value
            customApps:
            - customApps
            - customApps
            name: name
            id: id
            entitlementSet:
            - entitlementSet
            - entitlementSet
            shipTo: shipTo
          shipTo: shipTo
        name: Clarivate
        enterpriseId: ACT-00000000
        accountOwner:
          ref: /SFDCInternalUsers/kadri.nebiu@clarivate.com
          name: Kadri Nebiu
          email: kadri.nebiu@clarivate.com
        portalInfo:
        - approved: true
          appInfo:
            changedDate: changedDate
            requesterEmails:
            - requesterEmails
            - requesterEmails
            name: name
            description: description
            id: id
          apiProductName: apiProductName
          subscriptionId: subscriptionId
          plan: plan
        - approved: true
          appInfo:
            changedDate: changedDate
            requesterEmails:
            - requesterEmails
            - requesterEmails
            name: name
            description: description
            id: id
          apiProductName: apiProductName
          subscriptionId: subscriptionId
          plan: plan
        sfdcOpportunities:
        - opportunityIDNumber: OPP-00000000
          ref: /SFDCOpportunities/OPP-00000000
          opportunityName: UNIVERSITE DE POITIERS - Web of Science - 2022
          stage: stage
          type: type
          contractExpireDate: contractExpireDate
        - opportunityIDNumber: OPP-00000000
          ref: /SFDCOpportunities/OPP-00000000
          opportunityName: UNIVERSITE DE POITIERS - Web of Science - 2022
          stage: stage
          type: type
          contractExpireDate: contractExpireDate
      properties:
        name:
          example: Clarivate
          type: string
        enterpriseId:
          example: ACT-00000000
          type: string
        emailDomain:
          example: slv.vic.gov.au
          type: string
        accountOwner:
          $ref: '#/components/schemas/InternalUserReference'
        sfdcOpportunities:
          items:
            $ref: '#/components/schemas/SFDCOpportunityReference'
          type: array
        caesarReference:
          $ref: '#/components/schemas/CaesarIdSetReference'
        portalInfo:
          items:
            $ref: '#/components/schemas/Subscription'
          type: array
      type: object
    SFDCAccountList:
      example:
        hits:
        - accountRef:
            ref: /SFDCAccounts/ACT-0000000
            accountName: Clarivate
            enterpriseId: ACT-0000000
          matches:
          - field: field
            value:
            - value
            - value
          - field: field
            value:
            - value
            - value
        - accountRef:
            ref: /SFDCAccounts/ACT-0000000
            accountName: Clarivate
            enterpriseId: ACT-0000000
          matches:
          - field: field
            value:
            - value
            - value
          - field: field
            value:
            - value
            - value
        metadata:
          total: 0
          limit: 1
          page: 6
      properties:
        metadata:
          $ref: '#/components/schemas/Metadata'
        hits:
          items:
            $ref: '#/components/schemas/SFDCAccountListRecord'
          type: array
      type: object
    SFDCOpportunity:
      example:
        opportunityIDNumber: OPP-00000000
        sfdcAccount:
          ref: /SFDCAccounts/ACT-0000000
          accountName: Clarivate
          enterpriseID: ACT-0000000
        emailDomain: emailDomain
        opportunityName: UNIVERSITE DE POITIERS - Web of Science - 2022
        opportunityOwner:
          ref: /SFDCInternalUsers/kadri.nebiu@clarivate.com
          name: Kadri Nebiu
          email: kadri.nebiu@clarivate.com
        type: type
        contractExpireDate: contractExpireDate
        products:
        - sfdcProductCode: "45021425"
          quoteLines:
          - quoteLines
          - quoteLines
          sfdcProductName: Journals API - Data Integration
          primaryQuote: primaryQuote
          devPortalSubscriptionItem:
          - approved: true
            appInfo:
              changedDate: changedDate
              requesterEmails:
              - requesterEmails
              - requesterEmails
              name: name
              description: description
              id: id
            apiProductName: apiProductName
            subscriptionId: subscriptionId
            plan: plan
          - approved: true
            appInfo:
              changedDate: changedDate
              requesterEmails:
              - requesterEmails
              - requesterEmails
              name: name
              description: description
              id: id
            apiProductName: apiProductName
            subscriptionId: subscriptionId
            plan: plan
        - sfdcProductCode: "45021425"
          quoteLines:
          - quoteLines
          - quoteLines
          sfdcProductName: Journals API - Data Integration
          primaryQuote: primaryQuote
          devPortalSubscriptionItem:
          - approved: true
            appInfo:
              changedDate: changedDate
              requesterEmails:
              - requesterEmails
              - requesterEmails
              name: name
              description: description
              id: id
            apiProductName: apiProductName
            subscriptionId: subscriptionId
            plan: plan
          - approved: true
            appInfo:
              changedDate: changedDate
              requesterEmails:
              - requesterEmails
              - requesterEmails
              name: name
              description: description
              id: id
            apiProductName: apiProductName
            subscriptionId: subscriptionId
            plan: plan
        closeDate: closeDate
        opportunityID: opportunityID
        contractEffectiveDate: contractEffectiveDate
        createdDate: createdDate
        stage: stage
      properties:
        opportunityIDNumber:
          description: Opportunity ID Number that is can be used in emails
          example: OPP-00000000
          type: string
        opportunityName:
          description: Opportunity name
          example: UNIVERSITE DE POITIERS - Web of Science - 2022
          type: string
        opportunityID:
          type: string
        type:
          description: Type of opportunity, New, Renewal, Amendment, etc.
          type: string
        contractExpireDate:
          type: string
        contractEffectiveDate:
          type: string
        closeDate:
          type: string
        createdDate:
          type: string
        stage:
          type: string
        sfdcAccount:
          $ref: '#/components/schemas/SFDCOpportunity_sfdcAccount'
        opportunityOwner:
          $ref: '#/components/schemas/SFDCOpportunity_opportunityOwner'
        emailDomain:
          type: string
        products:
          items:
            $ref: '#/components/schemas/OpportunityAPIItem'
          type: array
      type: object
    OpportunityAPIItem:
      example:
        sfdcProductCode: "45021425"
        quoteLines:
        - quoteLines
        - quoteLines
        sfdcProductName: Journals API - Data Integration
        primaryQuote: primaryQuote
        devPortalSubscriptionItem:
        - approved: true
          appInfo:
            changedDate: changedDate
            requesterEmails:
            - requesterEmails
            - requesterEmails
            name: name
            description: description
            id: id
          apiProductName: apiProductName
          subscriptionId: subscriptionId
          plan: plan
        - approved: true
          appInfo:
            changedDate: changedDate
            requesterEmails:
            - requesterEmails
            - requesterEmails
            name: name
            description: description
            id: id
          apiProductName: apiProductName
          subscriptionId: subscriptionId
          plan: plan
      properties:
        sfdcProductCode:
          example: "45021425"
          type: string
        sfdcProductName:
          example: Journals API - Data Integration
          type: string
        primaryQuote:
          type: string
        quoteLines:
          items:
            type: string
          type: array
        devPortalSubscriptionItem:
          items:
            $ref: '#/components/schemas/Subscription'
          type: array
      type: object
    CaesarIdSetReference:
      description: Caesar reference that is used when searching other entitites
      example:
        trialEnd: trialEnd
        soldTo: soldTo
        accountName: accountName
        trialStart: trialStart
        customerId: customerId
        identifierSet:
        - soldTo: soldTo
          identifierList:
          - kind: kind
            value: value
          - kind: kind
            value: value
          customApps:
          - customApps
          - customApps
          name: name
          id: id
          entitlementSet:
          - entitlementSet
          - entitlementSet
          shipTo: shipTo
        - soldTo: soldTo
          identifierList:
          - kind: kind
            value: value
          - kind: kind
            value: value
          customApps:
          - customApps
          - customApps
          name: name
          id: id
          entitlementSet:
          - entitlementSet
          - entitlementSet
          shipTo: shipTo
        shipTo: shipTo
      properties:
        accountName:
          type: string
        customerId:
          type: string
        shipTo:
          type: string
        soldTo:
          type: string
        trialStart:
          type: string
        trialEnd:
          type: string
        identifierSet:
          items:
            $ref: '#/components/schemas/CaesarIdSetReference_identifierSet'
          type: array
      type: object
    InternalUserList:
      example:
        hits:
        - internalUserRef:
            ref: /SFDCInternalUsers/kadri.nebiu@clarivate.com
            name: Kadri Nebiu
            email: kadri.nebiu@clarivate.com
          matches:
          - field: field
            value:
            - value
            - value
          - field: field
            value:
            - value
            - value
        - internalUserRef:
            ref: /SFDCInternalUsers/kadri.nebiu@clarivate.com
            name: Kadri Nebiu
            email: kadri.nebiu@clarivate.com
          matches:
          - field: field
            value:
            - value
            - value
          - field: field
            value:
            - value
            - value
        metadata:
          total: 0
          limit: 1
          page: 6
      properties:
        metadata:
          $ref: '#/components/schemas/Metadata'
        hits:
          items:
            $ref: '#/components/schemas/InternalUserListRecord'
          type: array
      type: object
    InternalUserListRecord:
      example:
        internalUserRef:
          ref: /SFDCInternalUsers/kadri.nebiu@clarivate.com
          name: Kadri Nebiu
          email: kadri.nebiu@clarivate.com
        matches:
        - field: field
          value:
          - value
          - value
        - field: field
          value:
          - value
          - value
      properties:
        internalUserRef:
          $ref: '#/components/schemas/InternalUserReference'
        matches:
          items:
            $ref: '#/components/schemas/SearchMatch'
          type: array
      type: object
    InternalUserReference:
      example:
        ref: /SFDCInternalUsers/kadri.nebiu@clarivate.com
        name: Kadri Nebiu
        email: kadri.nebiu@clarivate.com
      properties:
        email:
          example: kadri.nebiu@clarivate.com
          type: string
        name:
          example: Kadri Nebiu
          type: string
        ref:
          example: /SFDCInternalUsers/kadri.nebiu@clarivate.com
          type: string
      type: object
    InternalUser:
      properties:
        email:
          example: kadri.nebiu@clarivate.com
          type: string
        name:
          example: Kadri Nebiu
          type: string
        sfdcAccounts:
          items:
            $ref: '#/components/schemas/SFDCAccountReference'
          type: array
      type: object
    SFDCAccountReference:
      description: SFDC account reference that is used when searching other entitites
      example:
        ref: /SFDCAccounts/ACT-0000000
        accountName: Clarivate
        enterpriseId: ACT-0000000
      properties:
        enterpriseId:
          example: ACT-0000000
          type: string
        accountName:
          example: Clarivate
          type: string
        ref:
          example: /SFDCAccounts/ACT-0000000
          type: string
      type: object
    Metadata:
      description: Information about total number of items in the retrieve, number
        of recodrs on the page, and the page number.
      example:
        total: 0
        limit: 1
        page: 6
      properties:
        total:
          description: Total number of records for the request.
          format: int32
          type: integer
        page:
          description: Page number (default is 1)
          format: int32
          type: integer
        limit:
          description: Number of records on a page (default is 10).
          format: int32
          type: integer
      type: object
    SearchMatch:
      description: Displays the field and value matched to the search string
      example:
        field: field
        value:
        - value
        - value
      properties:
        field:
          description: Name of the matched field
          type: string
        value:
          description: Array of matched values (if several) with the HTML highligthing
          items:
            type: string
          type: array
      type: object
    Task:
      example:
        startDt: 2000-01-23T04:56:07.000+00:00
        endDt: 2000-01-23T04:56:07.000+00:00
        id: 0
        state: state
        message: message
      properties:
        id:
          format: int32
          type: integer
        state:
          type: string
        startDt:
          format: date-time
          type: string
        endDt:
          format: date-time
          type: string
        message:
          type: string
      type: object
    Subscriptions:
      items:
        $ref: '#/components/schemas/Subscription'
      type: array
    Subscription:
      example:
        approved: true
        appInfo:
          changedDate: changedDate
          requesterEmails:
          - requesterEmails
          - requesterEmails
          name: name
          description: description
          id: id
        apiProductName: apiProductName
        subscriptionId: subscriptionId
        plan: plan
      properties:
        subscriptionId:
          type: string
        appInfo:
          $ref: '#/components/schemas/Subscription_appInfo'
        apiProductName:
          type: string
        plan:
          type: string
        approved:
          type: boolean
      type: object
    inline_object:
      properties:
        file:
          format: binary
          type: string
      type: object
    inline_object_1:
      properties:
        file:
          format: binary
          type: string
      type: object
    inline_object_2:
      properties:
        file:
          format: binary
          type: string
      type: object
    SFDCOpportunity_sfdcAccount:
      example:
        ref: /SFDCAccounts/ACT-0000000
        accountName: Clarivate
        enterpriseID: ACT-0000000
      properties:
        enterpriseID:
          example: ACT-0000000
          type: string
        accountName:
          example: Clarivate
          type: string
        ref:
          example: /SFDCAccounts/ACT-0000000
          type: string
      type: object
    SFDCOpportunity_opportunityOwner:
      example:
        ref: /SFDCInternalUsers/kadri.nebiu@clarivate.com
        name: Kadri Nebiu
        email: kadri.nebiu@clarivate.com
      properties:
        email:
          example: kadri.nebiu@clarivate.com
          type: string
        name:
          example: Kadri Nebiu
          type: string
        ref:
          example: /SFDCInternalUsers/kadri.nebiu@clarivate.com
          type: string
      type: object
    CaesarIdSetReference_identifierList:
      example:
        kind: kind
        value: value
      properties:
        kind:
          type: string
        value:
          type: string
      required:
      - kind
      - value
      type: object
    CaesarIdSetReference_identifierSet:
      example:
        soldTo: soldTo
        identifierList:
        - kind: kind
          value: value
        - kind: kind
          value: value
        customApps:
        - customApps
        - customApps
        name: name
        id: id
        entitlementSet:
        - entitlementSet
        - entitlementSet
        shipTo: shipTo
      properties:
        id:
          type: string
        name:
          type: string
        shipTo:
          type: string
        soldTo:
          type: string
        identifierList:
          items:
            $ref: '#/components/schemas/CaesarIdSetReference_identifierList'
          type: array
        customApps:
          items:
            type: string
          type: array
        entitlementSet:
          items:
            type: string
          type: array
      required:
      - entitlementSet
      - id
      - identifierList
      - name
      - shipTo
      - soldTo
      type: object
    Subscription_appInfo:
      example:
        changedDate: changedDate
        requesterEmails:
        - requesterEmails
        - requesterEmails
        name: name
        description: description
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        changedDate:
          type: string
        requesterEmails:
          items:
            type: string
          type: array
      type: object

